-- MySQL Script generated by MySQL Workbench
-- Mon May 18 23:09:17 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_sgi_emch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sgi_emch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sgi_emch` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `db_sgi_emch` ;

-- -----------------------------------------------------
-- Table `db_sgi_emch`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`area` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`area` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `codigo_area` VARCHAR(20) NOT NULL,
  `nombre_area` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `anio_vigencia` YEAR NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_area`),
  UNIQUE INDEX `uq_area_codigo` (`codigo_area` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Unidades y dependencias del EMCH';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`rol` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `uq_rol_nombre` (`nombre_rol` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Roles de acceso al sistema';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`usuario_sistema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`usuario_sistema` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`usuario_sistema` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `id_area` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `dni` CHAR(8) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'bcrypt hash, min cost 10',
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `ultimo_acceso` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `uq_usuario_dni` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `uq_usuario_user` (`username` ASC) VISIBLE,
  INDEX `idx_usuario_rol` (`id_rol` ASC) VISIBLE,
  INDEX `idx_usuario_area` (`id_area` ASC) VISIBLE,
  INDEX `idx_usuario_activo` (`activo` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_area`
    FOREIGN KEY (`id_area`)
    REFERENCES `db_sgi_emch`.`area` (`id_area`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `db_sgi_emch`.`rol` (`id_rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Usuarios con acceso al sistema DTIC';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`audit_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`audit_log` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`audit_log` (
  `id_log` BIGINT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL COMMENT 'NULL si es acción del sistema',
  `tabla_afectada` VARCHAR(50) NOT NULL,
  `operacion` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `registro_id` INT NOT NULL,
  `datos_anteriores` JSON NULL DEFAULT NULL COMMENT 'Estado antes del cambio (UPDATE/DELETE)',
  `datos_nuevos` JSON NULL DEFAULT NULL COMMENT 'Estado después del cambio (INSERT/UPDATE)',
  `ip_origen` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_accion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  INDEX `idx_audit_tabla` (`tabla_afectada` ASC, `operacion` ASC) VISIBLE,
  INDEX `idx_audit_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_audit_fecha` (`fecha_accion` ASC) VISIBLE,
  INDEX `idx_audit_registro` (`tabla_afectada` ASC, `registro_id` ASC) VISIBLE,
  CONSTRAINT `fk_audit_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_sgi_emch`.`usuario_sistema` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Log de auditoría inmutable de todas las operaciones'
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`tipo_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`tipo_equipo` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`tipo_equipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`),
  UNIQUE INDEX `uq_tipo_equipo_nombre` (`nombre_tipo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Categorías de equipos TIC';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`config_stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`config_stock` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`config_stock` (
  `id_config` INT NOT NULL AUTO_INCREMENT,
  `id_tipo` INT NOT NULL,
  `umbral_pct` TINYINT UNSIGNED NOT NULL DEFAULT '20' COMMENT 'Porcentaje mínimo de stock operativo',
  `id_usuario_config` INT NOT NULL,
  `fecha_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_config`),
  UNIQUE INDEX `uq_config_stock_tipo` (`id_tipo` ASC) VISIBLE,
  INDEX `fk_config_usuario` (`id_usuario_config` ASC) VISIBLE,
  CONSTRAINT `fk_config_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `db_sgi_emch`.`tipo_equipo` (`id_tipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_config_usuario`
    FOREIGN KEY (`id_usuario_config`)
    REFERENCES `db_sgi_emch`.`usuario_sistema` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Configuración de umbrales de stock por tipo de equipo';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`marca` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_marca`),
  UNIQUE INDEX `uq_marca_nombre` (`nombre_marca` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Fabricantes / marcas de equipos';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`modelo_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`modelo_equipo` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`modelo_equipo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `id_marca` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  `nombre_modelo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_modelo`),
  UNIQUE INDEX `uq_modelo_nombre` (`id_marca` ASC, `id_tipo` ASC, `nombre_modelo` ASC) VISIBLE,
  INDEX `idx_modelo_tipo` (`id_tipo` ASC) VISIBLE,
  INDEX `idx_modelo_marca` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `db_sgi_emch`.`marca` (`id_marca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_modelo_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `db_sgi_emch`.`tipo_equipo` (`id_tipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Modelos de equipos por marca y tipo';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`sistema_operativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`sistema_operativo` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`sistema_operativo` (
  `id_so` INT NOT NULL AUTO_INCREMENT,
  `nombre_so` VARCHAR(80) NOT NULL,
  `version_so` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_so`),
  UNIQUE INDEX `uq_so_nombre_version` (`nombre_so` ASC, `version_so` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Sistemas operativos registrados';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`equipo` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`equipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `codigo_ejercito` VARCHAR(20) NOT NULL COMMENT 'Código institucional único del ejército',
  `id_tipo` INT NOT NULL,
  `id_modelo` INT NOT NULL,
  `id_area` INT NOT NULL,
  `id_so` INT NOT NULL,
  `numero_serie` VARCHAR(80) NOT NULL,
  `nombre_responsable` VARCHAR(150) NOT NULL COMMENT 'Encargado del equipo (no es usuario del sistema)',
  `mac_address` VARCHAR(17) NULL DEFAULT NULL COMMENT 'Formato: AA:BB:CC:DD:EE:FF',
  `ip_address` VARCHAR(45) NULL DEFAULT NULL COMMENT 'IPv4 o IPv6',
  `tipo_red` ENUM('ETHERNET', 'WIFI', 'N/A') NOT NULL DEFAULT 'N/A',
  `estado` ENUM('EN_BODEGA', 'ASIGNADO', 'EN_REPARACION', 'PRESTADO', 'DADO_DE_BAJA') NOT NULL DEFAULT 'EN_BODEGA',
  `fecha_adquisicion` DATE NULL DEFAULT NULL,
  `fecha_registro` DATE NOT NULL DEFAULT (current_date()),
  `fecha_baja` DATE NULL DEFAULT NULL COMMENT 'Solo se llena cuando estado=DADO_DE_BAJA',
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_equipo`),
  UNIQUE INDEX `uq_equipo_codigo` (`codigo_ejercito` ASC) VISIBLE,
  UNIQUE INDEX `uq_equipo_serie` (`numero_serie` ASC) VISIBLE,
  UNIQUE INDEX `uq_equipo_mac` (`mac_address` ASC) VISIBLE,
  INDEX `fk_equipo_modelo` (`id_modelo` ASC) VISIBLE,
  INDEX `fk_equipo_so` (`id_so` ASC) VISIBLE,
  INDEX `idx_equipo_tipo` (`id_tipo` ASC) VISIBLE,
  INDEX `idx_equipo_area` (`id_area` ASC) VISIBLE,
  INDEX `idx_equipo_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_equipo_adquisicion` (`fecha_adquisicion` ASC) VISIBLE,
  INDEX `idx_equipo_antiguedad` (`fecha_adquisicion` ASC, `estado` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_area`
    FOREIGN KEY (`id_area`)
    REFERENCES `db_sgi_emch`.`area` (`id_area`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equipo_modelo`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `db_sgi_emch`.`modelo_equipo` (`id_modelo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equipo_so`
    FOREIGN KEY (`id_so`)
    REFERENCES `db_sgi_emch`.`sistema_operativo` (`id_so`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equipo_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `db_sgi_emch`.`tipo_equipo` (`id_tipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Equipos TIC del EMCH';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`especificacion_tecnica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`especificacion_tecnica` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`especificacion_tecnica` (
  `id_espec` INT NOT NULL AUTO_INCREMENT,
  `id_equipo` INT NOT NULL,
  `procesador` VARCHAR(150) NULL DEFAULT NULL,
  `nucleos` TINYINT UNSIGNED NULL DEFAULT NULL,
  `hilos` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ram_total_gb` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ram_marca` VARCHAR(50) NULL DEFAULT NULL,
  `ram_velocidad_mhz` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ram_modulos` TINYINT UNSIGNED NULL DEFAULT NULL,
  `disco_modelo` VARCHAR(100) NULL DEFAULT NULL,
  `disco_capacidad_gb` DECIMAL(8,2) NULL DEFAULT NULL,
  `disco_interface` VARCHAR(20) NULL DEFAULT NULL COMMENT 'SATA, NVMe, SSD, etc.',
  `disco_usado_gb` DECIMAL(8,2) NULL DEFAULT NULL,
  `disco_libre_gb` DECIMAL(8,2) NULL DEFAULT NULL,
  `gpu_marca` VARCHAR(50) NULL DEFAULT NULL,
  `gpu_modelo` VARCHAR(100) NULL DEFAULT NULL,
  `gpu_vram_gb` DECIMAL(4,2) NULL DEFAULT NULL,
  `monitor_marca` VARCHAR(50) NULL DEFAULT NULL,
  `monitor_modelo` VARCHAR(80) NULL DEFAULT NULL,
  `red_modelo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_espec`),
  UNIQUE INDEX `uq_espec_equipo` (`id_equipo` ASC) VISIBLE,
  CONSTRAINT `fk_espec_equipo`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `db_sgi_emch`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Especificaciones técnicas de hardware por equipo';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`historial_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`historial_estado` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`historial_estado` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `id_equipo` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `estado_anterior` ENUM('EN_BODEGA', 'ASIGNADO', 'EN_REPARACION', 'PRESTADO', 'DADO_DE_BAJA') NOT NULL,
  `estado_nuevo` ENUM('EN_BODEGA', 'ASIGNADO', 'EN_REPARACION', 'PRESTADO', 'DADO_DE_BAJA') NOT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_cambio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_historial`),
  INDEX `fk_hestado_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_hestado_equipo` (`id_equipo` ASC) VISIBLE,
  INDEX `idx_hestado_fecha` (`fecha_cambio` ASC) VISIBLE,
  CONSTRAINT `fk_hestado_equipo`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `db_sgi_emch`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hestado_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_sgi_emch`.`usuario_sistema` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Historial de cambios de estado de equipos';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`tipo_incidente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`tipo_incidente` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`tipo_incidente` (
  `id_tipo_incidente` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `tiempo_respuesta_min` SMALLINT UNSIGNED NOT NULL COMMENT 'SLA: minutos para primera respuesta',
  `tiempo_resolucion_min` SMALLINT UNSIGNED NOT NULL COMMENT 'SLA: minutos para resolver',
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_incidente`),
  UNIQUE INDEX `uq_tipo_incidente_nombre` (`nombre_tipo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Tipos de incidencias con parámetros SLA';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`ticket` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`ticket` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `numero_ticket` VARCHAR(20) NOT NULL COMMENT 'Formato: TKT-YYYYMM-NNNN',
  `id_equipo` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `id_tipo_incidente` INT NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `estado` ENUM('ABIERTO', 'EN_PROCESO', 'RESUELTO', 'CERRADO') NOT NULL DEFAULT 'ABIERTO',
  `prioridad` ENUM('BAJA', 'MEDIA', 'ALTA', 'CRITICA') NOT NULL DEFAULT 'MEDIA',
  `fecha_apertura` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_respuesta` TIMESTAMP NULL DEFAULT NULL,
  `fecha_resolucion` TIMESTAMP NULL DEFAULT NULL,
  `fecha_cierre` TIMESTAMP NULL DEFAULT NULL,
  `fuera_de_sla` TINYINT(1) NOT NULL DEFAULT '0',
  `pdf_acta_path` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ticket`),
  UNIQUE INDEX `uq_ticket_numero` (`numero_ticket` ASC) VISIBLE,
  INDEX `fk_ticket_tipo_inc` (`id_tipo_incidente` ASC) VISIBLE,
  INDEX `idx_ticket_equipo` (`id_equipo` ASC) VISIBLE,
  INDEX `idx_ticket_tecnico` (`id_tecnico` ASC) VISIBLE,
  INDEX `idx_ticket_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_ticket_apertura` (`fecha_apertura` ASC) VISIBLE,
  INDEX `idx_ticket_sla` (`fuera_de_sla` ASC, `estado` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_equipo`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `db_sgi_emch`.`equipo` (`id_equipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `db_sgi_emch`.`usuario_sistema` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_tipo_inc`
    FOREIGN KEY (`id_tipo_incidente`)
    REFERENCES `db_sgi_emch`.`tipo_incidente` (`id_tipo_incidente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Tickets de incidentes TIC';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`historial_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`historial_ticket` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`historial_ticket` (
  `id_hist_ticket` INT NOT NULL AUTO_INCREMENT,
  `id_ticket` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `estado_anterior` ENUM('ABIERTO', 'EN_PROCESO', 'RESUELTO', 'CERRADO') NOT NULL,
  `estado_nuevo` ENUM('ABIERTO', 'EN_PROCESO', 'RESUELTO', 'CERRADO') NOT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `fecha_cambio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_hist_ticket`),
  INDEX `fk_hticket_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_hticket_ticket` (`id_ticket` ASC) VISIBLE,
  INDEX `idx_hticket_fecha` (`fecha_cambio` ASC) VISIBLE,
  CONSTRAINT `fk_hticket_ticket`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `db_sgi_emch`.`ticket` (`id_ticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hticket_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_sgi_emch`.`usuario_sistema` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Historial de cambios en tickets';


-- -----------------------------------------------------
-- Table `db_sgi_emch`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`notificacion` (
  `id_notif` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `tipo_notif` ENUM('STOCK_CRITICO', 'SLA_VENCIDO', 'TICKET_ASIGNADO', 'INFO') NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `mensaje` TEXT NULL DEFAULT NULL,
  `leida` TINYINT(1) NOT NULL DEFAULT '0',
  `url_accion` VARCHAR(500) NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_notif`),
  INDEX `idx_notif_usuario` (`id_usuario` ASC, `leida` ASC) VISIBLE,
  INDEX `idx_notif_tipo` (`tipo_notif` ASC) VISIBLE,
  INDEX `idx_notif_fecha` (`fecha_creacion` ASC) VISIBLE,
  CONSTRAINT `fk_notif_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_sgi_emch`.`usuario_sistema` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Notificaciones del sistema para usuarios';

USE `db_sgi_emch` ;

-- -----------------------------------------------------
-- Placeholder table for view `db_sgi_emch`.`v_dashboard_resumen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`v_dashboard_resumen` (`nombre_tipo` INT, `total` INT, `asignados` INT, `en_bodega` INT, `en_reparacion` INT, `dados_de_baja` INT, `stock_operativo` INT, `umbral_stock_pct` INT, `pct_operativo` INT, `equipos_mayores_5_anios` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db_sgi_emch`.`v_inventario_completo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`v_inventario_completo` (`id_equipo` INT, `codigo_ejercito` INT, `tipo` INT, `marca` INT, `modelo` INT, `codigo_area` INT, `area` INT, `nombre_so` INT, `version_so` INT, `numero_serie` INT, `nombre_responsable` INT, `mac_address` INT, `ip_address` INT, `tipo_red` INT, `estado` INT, `fecha_adquisicion` INT, `anios_antiguedad` INT, `fecha_registro` INT, `fecha_baja` INT, `observaciones` INT, `procesador` INT, `nucleos` INT, `hilos` INT, `ram_total_gb` INT, `ram_marca` INT, `ram_velocidad_mhz` INT, `disco_capacidad_gb` INT, `disco_usado_gb` INT, `disco_libre_gb` INT, `disco_uso_pct` INT, `gpu_marca` INT, `gpu_modelo` INT, `monitor_marca` INT, `monitor_modelo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db_sgi_emch`.`v_stock_critico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`v_stock_critico` (`id_tipo` INT, `nombre_tipo` INT, `total_equipos` INT, `stock_operativo` INT, `umbral_pct` INT, `pct_actual` INT, `en_alerta` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db_sgi_emch`.`v_tickets_activos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sgi_emch`.`v_tickets_activos` (`id_ticket` INT, `numero_ticket` INT, `codigo_ejercito` INT, `nombre_area` INT, `tecnico` INT, `tipo_incidente` INT, `titulo` INT, `estado` INT, `prioridad` INT, `fecha_apertura` INT, `sla_minutos` INT, `minutos_transcurridos` INT, `minutos_restantes_sla` INT, `sla_vencido` INT, `fuera_de_sla` INT);

-- -----------------------------------------------------
-- procedure sp_generar_numero_ticket
-- -----------------------------------------------------

USE `db_sgi_emch`;
DROP procedure IF EXISTS `db_sgi_emch`.`sp_generar_numero_ticket`;

DELIMITER $$
USE `db_sgi_emch`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_generar_numero_ticket`(OUT p_numero VARCHAR(20))
BEGIN
  DECLARE v_anio_mes CHAR(6);
  DECLARE v_secuencia INT;

  SET v_anio_mes = DATE_FORMAT(NOW(), '%Y%m');

  SELECT COALESCE(MAX(
    CAST(SUBSTRING(numero_ticket, 12) AS UNSIGNED)
  ), 0) + 1
  INTO v_secuencia
  FROM ticket
  WHERE numero_ticket LIKE CONCAT('TKT-', v_anio_mes, '-%');

  SET p_numero = CONCAT('TKT-', v_anio_mes, '-', LPAD(v_secuencia, 4, '0'));
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_verificar_stock_critico
-- -----------------------------------------------------

USE `db_sgi_emch`;
DROP procedure IF EXISTS `db_sgi_emch`.`sp_verificar_stock_critico`;

DELIMITER $$
USE `db_sgi_emch`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_verificar_stock_critico`(IN p_id_tipo INT)
BEGIN
  DECLARE v_total       INT;
  DECLARE v_operativo   INT;
  DECLARE v_umbral      TINYINT;
  DECLARE v_pct_actual  DECIMAL(5,2);
  DECLARE v_nombre_tipo VARCHAR(50);

  SELECT
    te.nombre_tipo,
    COUNT(e.id_equipo),
    SUM(e.estado <> 'DADO_DE_BAJA'),
    cs.umbral_pct
  INTO v_nombre_tipo, v_total, v_operativo, v_umbral
  FROM tipo_equipo te
  LEFT JOIN equipo e      ON te.id_tipo = e.id_tipo
  LEFT JOIN config_stock cs ON te.id_tipo = cs.id_tipo
  WHERE te.id_tipo = p_id_tipo
  GROUP BY te.id_tipo, te.nombre_tipo, cs.umbral_pct;

  SET v_pct_actual = ROUND(v_operativo * 100.0 / NULLIF(v_total, 0), 1);

  -- Si el stock está por debajo del umbral, notificar a todos los admins y jefe DTIC
  IF v_pct_actual < v_umbral THEN
    INSERT INTO notificacion (id_usuario, tipo_notif, titulo, mensaje, url_accion)
    SELECT
      u.id_usuario,
      'STOCK_CRITICO',
      CONCAT('⚠️ Stock crítico: ', v_nombre_tipo),
      CONCAT(
        'El stock operativo de ', v_nombre_tipo,
        ' está en ', v_pct_actual, '% (',
        v_operativo, ' de ', v_total,
        ' equipos). Umbral mínimo configurado: ', v_umbral, '%.'
      ),
      CONCAT('/inventario?tipo=', p_id_tipo)
    FROM usuario_sistema u
    JOIN rol r ON u.id_rol = r.id_rol
    WHERE r.nombre_rol IN ('Administrador', 'Jefe DTIC')
      AND u.activo = 1;
  END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `db_sgi_emch`.`v_dashboard_resumen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`v_dashboard_resumen`;
DROP VIEW IF EXISTS `db_sgi_emch`.`v_dashboard_resumen` ;
USE `db_sgi_emch`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `db_sgi_emch`.`v_dashboard_resumen` AS select `te`.`nombre_tipo` AS `nombre_tipo`,count(0) AS `total`,sum((`e`.`estado` = 'ASIGNADO')) AS `asignados`,sum((`e`.`estado` = 'EN_BODEGA')) AS `en_bodega`,sum((`e`.`estado` = 'EN_REPARACION')) AS `en_reparacion`,sum((`e`.`estado` = 'DADO_DE_BAJA')) AS `dados_de_baja`,sum((`e`.`estado` <> 'DADO_DE_BAJA')) AS `stock_operativo`,`cs`.`umbral_pct` AS `umbral_stock_pct`,round(((sum((`e`.`estado` <> 'DADO_DE_BAJA')) * 100.0) / nullif(count(0),0)),1) AS `pct_operativo`,sum(((timestampdiff(YEAR,`e`.`fecha_adquisicion`,curdate()) >= 5) and (`e`.`estado` <> 'DADO_DE_BAJA'))) AS `equipos_mayores_5_anios` from ((`db_sgi_emch`.`equipo` `e` join `db_sgi_emch`.`tipo_equipo` `te` on((`e`.`id_tipo` = `te`.`id_tipo`))) left join `db_sgi_emch`.`config_stock` `cs` on((`cs`.`id_tipo` = `te`.`id_tipo`))) group by `te`.`id_tipo`,`te`.`nombre_tipo`,`cs`.`umbral_pct`;

-- -----------------------------------------------------
-- View `db_sgi_emch`.`v_inventario_completo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`v_inventario_completo`;
DROP VIEW IF EXISTS `db_sgi_emch`.`v_inventario_completo` ;
USE `db_sgi_emch`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `db_sgi_emch`.`v_inventario_completo` AS select `e`.`id_equipo` AS `id_equipo`,`e`.`codigo_ejercito` AS `codigo_ejercito`,`te`.`nombre_tipo` AS `tipo`,`ma`.`nombre_marca` AS `marca`,`me`.`nombre_modelo` AS `modelo`,`a`.`codigo_area` AS `codigo_area`,`a`.`nombre_area` AS `area`,`so`.`nombre_so` AS `nombre_so`,`so`.`version_so` AS `version_so`,`e`.`numero_serie` AS `numero_serie`,`e`.`nombre_responsable` AS `nombre_responsable`,`e`.`mac_address` AS `mac_address`,`e`.`ip_address` AS `ip_address`,`e`.`tipo_red` AS `tipo_red`,`e`.`estado` AS `estado`,`e`.`fecha_adquisicion` AS `fecha_adquisicion`,timestampdiff(YEAR,`e`.`fecha_adquisicion`,curdate()) AS `anios_antiguedad`,`e`.`fecha_registro` AS `fecha_registro`,`e`.`fecha_baja` AS `fecha_baja`,`e`.`observaciones` AS `observaciones`,`et`.`procesador` AS `procesador`,`et`.`nucleos` AS `nucleos`,`et`.`hilos` AS `hilos`,`et`.`ram_total_gb` AS `ram_total_gb`,`et`.`ram_marca` AS `ram_marca`,`et`.`ram_velocidad_mhz` AS `ram_velocidad_mhz`,`et`.`disco_capacidad_gb` AS `disco_capacidad_gb`,`et`.`disco_usado_gb` AS `disco_usado_gb`,`et`.`disco_libre_gb` AS `disco_libre_gb`,round(((`et`.`disco_usado_gb` / nullif(`et`.`disco_capacidad_gb`,0)) * 100),1) AS `disco_uso_pct`,`et`.`gpu_marca` AS `gpu_marca`,`et`.`gpu_modelo` AS `gpu_modelo`,`et`.`monitor_marca` AS `monitor_marca`,`et`.`monitor_modelo` AS `monitor_modelo` from ((((((`db_sgi_emch`.`equipo` `e` join `db_sgi_emch`.`tipo_equipo` `te` on((`e`.`id_tipo` = `te`.`id_tipo`))) join `db_sgi_emch`.`modelo_equipo` `me` on((`e`.`id_modelo` = `me`.`id_modelo`))) join `db_sgi_emch`.`marca` `ma` on((`me`.`id_marca` = `ma`.`id_marca`))) join `db_sgi_emch`.`area` `a` on((`e`.`id_area` = `a`.`id_area`))) join `db_sgi_emch`.`sistema_operativo` `so` on((`e`.`id_so` = `so`.`id_so`))) left join `db_sgi_emch`.`especificacion_tecnica` `et` on((`e`.`id_equipo` = `et`.`id_equipo`)));

-- -----------------------------------------------------
-- View `db_sgi_emch`.`v_stock_critico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`v_stock_critico`;
DROP VIEW IF EXISTS `db_sgi_emch`.`v_stock_critico` ;
USE `db_sgi_emch`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `db_sgi_emch`.`v_stock_critico` AS select `te`.`id_tipo` AS `id_tipo`,`te`.`nombre_tipo` AS `nombre_tipo`,count(`e`.`id_equipo`) AS `total_equipos`,sum((`e`.`estado` <> 'DADO_DE_BAJA')) AS `stock_operativo`,`cs`.`umbral_pct` AS `umbral_pct`,round(((sum((`e`.`estado` <> 'DADO_DE_BAJA')) * 100.0) / nullif(count(`e`.`id_equipo`),0)),1) AS `pct_actual`,(case when (round(((sum((`e`.`estado` <> 'DADO_DE_BAJA')) * 100.0) / nullif(count(`e`.`id_equipo`),0)),1) < `cs`.`umbral_pct`) then 1 else 0 end) AS `en_alerta` from ((`db_sgi_emch`.`tipo_equipo` `te` left join `db_sgi_emch`.`equipo` `e` on((`te`.`id_tipo` = `e`.`id_tipo`))) left join `db_sgi_emch`.`config_stock` `cs` on((`te`.`id_tipo` = `cs`.`id_tipo`))) group by `te`.`id_tipo`,`te`.`nombre_tipo`,`cs`.`umbral_pct` having (`en_alerta` = 1);

-- -----------------------------------------------------
-- View `db_sgi_emch`.`v_tickets_activos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sgi_emch`.`v_tickets_activos`;
DROP VIEW IF EXISTS `db_sgi_emch`.`v_tickets_activos` ;
USE `db_sgi_emch`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `db_sgi_emch`.`v_tickets_activos` AS select `t`.`id_ticket` AS `id_ticket`,`t`.`numero_ticket` AS `numero_ticket`,`e`.`codigo_ejercito` AS `codigo_ejercito`,`a`.`nombre_area` AS `nombre_area`,concat(`u`.`nombres`,' ',`u`.`apellidos`) AS `tecnico`,`ti`.`nombre_tipo` AS `tipo_incidente`,`t`.`titulo` AS `titulo`,`t`.`estado` AS `estado`,`t`.`prioridad` AS `prioridad`,`t`.`fecha_apertura` AS `fecha_apertura`,`ti`.`tiempo_resolucion_min` AS `sla_minutos`,timestampdiff(MINUTE,`t`.`fecha_apertura`,now()) AS `minutos_transcurridos`,(CAST(`ti`.`tiempo_resolucion_min` AS SIGNED) - timestampdiff(MINUTE,`t`.`fecha_apertura`,now())) AS `minutos_restantes_sla`,(case when (timestampdiff(MINUTE,`t`.`fecha_apertura`,now()) > `ti`.`tiempo_resolucion_min`) then 1 else 0 end) AS `sla_vencido`,`t`.`fuera_de_sla` AS `fuera_de_sla` from ((((`db_sgi_emch`.`ticket` `t` join `db_sgi_emch`.`equipo` `e` on((`t`.`id_equipo` = `e`.`id_equipo`))) join `db_sgi_emch`.`area` `a` on((`e`.`id_area` = `a`.`id_area`))) join `db_sgi_emch`.`usuario_sistema` `u` on((`t`.`id_tecnico` = `u`.`id_usuario`))) join `db_sgi_emch`.`tipo_incidente` `ti` on((`t`.`id_tipo_incidente` = `ti`.`id_tipo_incidente`))) where (`t`.`estado` in ('ABIERTO','EN_PROCESO'));
USE `db_sgi_emch`;

DELIMITER $$

USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_audit_usuario_update` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_audit_usuario_update`
AFTER UPDATE ON `db_sgi_emch`.`usuario_sistema`
FOR EACH ROW
BEGIN
  INSERT INTO audit_log (
    id_usuario, tabla_afectada, operacion, registro_id,
    datos_anteriores, datos_nuevos, ip_origen
  ) VALUES (
    @id_usuario_activo,
    'usuario_sistema',
    'UPDATE',
    NEW.id_usuario,
    JSON_OBJECT('username', OLD.username, 'id_rol', OLD.id_rol, 'activo', OLD.activo),
    JSON_OBJECT('username', NEW.username, 'id_rol', NEW.id_rol, 'activo', NEW.activo),
    @ip_cliente
  );
END$$


USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_audit_equipo_delete` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_audit_equipo_delete`
BEFORE DELETE ON `db_sgi_emch`.`equipo`
FOR EACH ROW
BEGIN
  INSERT INTO audit_log (
    id_usuario, tabla_afectada, operacion, registro_id,
    datos_anteriores, datos_nuevos, ip_origen
  ) VALUES (
    @id_usuario_activo,
    'equipo',
    'DELETE',
    OLD.id_equipo,
    JSON_OBJECT(
      'codigo_ejercito', OLD.codigo_ejercito,
      'numero_serie', OLD.numero_serie,
      'estado', OLD.estado
    ),
    NULL,
    @ip_cliente
  );
END$$


USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_audit_equipo_update` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_audit_equipo_update`
AFTER UPDATE ON `db_sgi_emch`.`equipo`
FOR EACH ROW
BEGIN
  INSERT INTO audit_log (
    id_usuario, tabla_afectada, operacion, registro_id,
    datos_anteriores, datos_nuevos, ip_origen
  ) VALUES (
    @id_usuario_activo,
    'equipo',
    'UPDATE',
    NEW.id_equipo,
    JSON_OBJECT(
      'codigo_ejercito', OLD.codigo_ejercito,
      'estado', OLD.estado,
      'id_area', OLD.id_area,
      'nombre_responsable', OLD.nombre_responsable
    ),
    JSON_OBJECT(
      'codigo_ejercito', NEW.codigo_ejercito,
      'estado', NEW.estado,
      'id_area', NEW.id_area,
      'nombre_responsable', NEW.nombre_responsable
    ),
    @ip_cliente
  );
END$$


USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_equipo_after_insert` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_equipo_after_insert`
AFTER INSERT ON `db_sgi_emch`.`equipo`
FOR EACH ROW
BEGIN
  INSERT INTO especificacion_tecnica (id_equipo)
  VALUES (NEW.id_equipo);
END$$


USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_equipo_baja` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_equipo_baja`
BEFORE UPDATE ON `db_sgi_emch`.`equipo`
FOR EACH ROW
BEGIN
  IF NEW.estado = 'DADO_DE_BAJA' AND OLD.estado <> 'DADO_DE_BAJA' THEN
    SET NEW.fecha_baja = CURDATE();
  END IF;
  -- Limpiar fecha_baja si se reactiva (corrección de error)
  IF NEW.estado <> 'DADO_DE_BAJA' AND OLD.estado = 'DADO_DE_BAJA' THEN
    SET NEW.fecha_baja = NULL;
  END IF;
END$$


USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_equipo_estado_update` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_equipo_estado_update`
AFTER UPDATE ON `db_sgi_emch`.`equipo`
FOR EACH ROW
BEGIN
  IF OLD.estado <> NEW.estado THEN
    INSERT INTO historial_estado (
      id_equipo, id_usuario, estado_anterior, estado_nuevo, motivo
    ) VALUES (
      NEW.id_equipo,
      COALESCE(@id_usuario_activo, 1),
      OLD.estado,
      NEW.estado,
      'Cambio registrado automáticamente'
    );
  END IF;
END$$


USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_ticket_historial` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_ticket_historial`
AFTER UPDATE ON `db_sgi_emch`.`ticket`
FOR EACH ROW
BEGIN
  IF OLD.estado <> NEW.estado THEN
    INSERT INTO historial_ticket (
      id_ticket, id_usuario, estado_anterior, estado_nuevo, comentario
    ) VALUES (
      NEW.id_ticket,
      COALESCE(@id_usuario_activo, 1),
      OLD.estado,
      NEW.estado,
      'Cambio de estado automático'
    );
  END IF;
END$$


USE `db_sgi_emch`$$
DROP TRIGGER IF EXISTS `db_sgi_emch`.`trg_ticket_sla_check` $$
USE `db_sgi_emch`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_sgi_emch`.`trg_ticket_sla_check`
BEFORE UPDATE ON `db_sgi_emch`.`ticket`
FOR EACH ROW
BEGIN
  DECLARE v_tiempo_sla INT;

  IF NEW.fecha_resolucion IS NOT NULL AND OLD.fecha_resolucion IS NULL THEN
    SELECT tiempo_resolucion_min INTO v_tiempo_sla
    FROM tipo_incidente
    WHERE id_tipo_incidente = NEW.id_tipo_incidente;

    IF TIMESTAMPDIFF(MINUTE, NEW.fecha_apertura, NEW.fecha_resolucion) > v_tiempo_sla THEN
      SET NEW.fuera_de_sla = 1;
    ELSE
      SET NEW.fuera_de_sla = 0;
    END IF;
  END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
